[workspace]
members = [
    "crates/*",
    "examples/clients",
    "examples/servers",
]
resolver = "2"

[workspace.dependencies]
mcp-core = { path = "./crates/mcp-core" }
mcp-macros = { path = "./crates/mcp-macros" }

[workspace.package]
edition = "2021"
license = "MIT"
